### Site metadata ###

site_name: forgex Docs
site_description: Official documentation for forgex project
site_url: https://docs.forgex.dev/

repo_url: https://github.com/DEVRhylme-Foundation/forgex
edit_uri: edit/main/docs/docs

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - toc.flow
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - ForgeX UI: ForgeX-ui.md
  - Project creation & default config:
    - Project init: creating-project/project-init.md
    - Makefile: creating-project/makefile.md
    - Air: creating-project/air.md
  - ForgeX Core:
    - Frameworks: ForgeX-core/frameworks.md
    - DB Drivers: ForgeX-core/db-drivers.md
  - Advanced Flag:
    - AF Usage: advanced-flag/advanced-flag.md
    - HTMX and Templ: advanced-flag/htmx-templ.md
    - Tailwind CSS: advanced-flag/tailwind.md
    - GoReleaser & GoTest CI: advanced-flag/goreleaser.md
    - Websocket: advanced-flag/websocket.md
    - Docker: advanced-flag/docker.md
  - Testing endpoints: 
    - Server: endpoints-test/server.md
    - DB Health Endpoints: 
       - SQL DBs: endpoints-test/sql.md
       - Redis: endpoints-test/redis.md
       - MongoDB: endpoints-test/mongo.md
    - Websocket: endpoints-test/websocket.md
    - Web Endpoint: endpoints-test/web.md

extra:
    social:
      - icon: fontawesome/brands/discord
        link: https://discord.com/invite/HHZMSCu
        name: Discord
      - icon: fontawesome/brands/twitch
        link: https://www.twitch.tv/melkey
        name: Twitch
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/@DEVRhylme-Foundation
        name: YouTube
      - icon: fontawesome/brands/twitter
        link: https://x.com/DEVRhylme-Foundation
        name: Twitter
    generator: false

copyright: Copyright &copy; 2024 Melkey
